image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp

ports:
  - port: 44380
    onOpen: open-preview
  - port: 44381
  - port: 44382